export const LOAD_RABBITS = 'LOAD_RABBITS';

export const AUTHORIZATION = 'AUTHORIZATION';

export const OPEN_AUTHORIZATION = 'TOGGLE_OPEN_AUTHORIZATION';

export const CREATE_RABBIT = 'CREATE_RABBIT';

export const REFACT_RABBIT = 'REFACT_RABBIT';


